# Generated by Django 6.1 on 2026-09-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='Registered contact phone number', max_length=20)),
                ('subject', models.CharField(help_text='Subject / Category of complaint (e.g., Red LOS Light, Slow Speed, Router Issue)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress / Tech Assigned'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Resolution details / technician note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
