# Generated by Django 6.1 on 2026-09-05 06:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 20 Mbps Fiber Pro', max_length=100)),
                ('speed_mbps', models.PositiveIntegerField(help_text='Speed in Mbps / MB')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('description', models.TextField(help_text='Short description of the package')),
                ('features', models.TextField(blank=True, help_text='Enter features separated by newlines (e.g. Unlimited Data, Zero Buffer 4K Streaming, 24/7 Fiber Support)')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight as Best Value / Most Popular')),
                ('is_active', models.BooleanField(default=True, help_text='Available for purchase on website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display sorting order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'speed_mbps'],
            },
        ),
        migrations.CreateModel(
            name='PackageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('speed_snapshot', models.PositiveIntegerField(default=0)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Package Activated'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='packages.internetpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
