# Generated by Django 6.1 on 2026-09-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetpackage',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Customizable package (2 to 30 Mbps)'),
        ),
    ]
