# Generated by Django 6.1 on 2026-09-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '⭐⭐⭐⭐⭐ 5 - Excellent'), (4, '⭐⭐⭐⭐ 4 - Very Good'), (3, '⭐⭐⭐ 3 - Good'), (2, '⭐⭐ 2 - Fair'), (1, '⭐ 1 - Poor')], default=5)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Show on website home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer Headline, e.g. Free Optical Fiber Installation', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Short subtext', max_length=200)),
                ('discount_tag', models.CharField(default='SPECIAL OFFER', help_text='e.g. 20% OFF, FREE ROUTER', max_length=50)),
                ('description', models.TextField(help_text='Offer terms or description')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_offers', to='packages.internetpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
